# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ondewo:hand-written-async-service
#
# This file is NOT generated by `make create_async_services`, and the marker above is what stops that
# target from overwriting it. The generator rewrites every ``self.stub.Rpc(...)`` into
# ``await self.stub.Rpc(...)``. That is correct for a unary RPC, because grpc.aio returns an awaitable
# ``UnaryUnaryCall`` — but ``Calls.StreamCallerStatus``, ``Calls.StreamListenerStatus`` and
# ``Calls.StreamScheduledCallerStatus`` are server-streaming, and grpc.aio returns a ``UnaryStreamCall``,
# which is an async ITERATOR and must not be awaited. A generated wrapper for them fails at runtime on the
# first call. Because the generator no longer touches this file, a method added to ``calls.py`` must be
# added here by hand as well.
from typing import AsyncIterator

from ondewo.vtsi import calls_pb2
from ondewo.vtsi.calls_pb2_grpc import CallsStub
from ondewo.vtsi.client.async_services_interface import AsyncServicesInterface


class Calls(AsyncServicesInterface):
    """
    A class representing the Calls service interface.

    This class provides methods to interact with the Calls service, which allows starting and managing
    callers, listeners, scheduled callers, and handling calls and audio files.

    Inherits from BaseServicesInterface.
    """

    @property
    def stub(self) -> CallsStub:
        """
        Get the gRPC stub for the Calls service.

        Returns:
            CallsStub: The gRPC stub for the Calls service.
        """
        stub: CallsStub = CallsStub(channel=self.grpc_channel)
        return stub

    async def start_caller(
        self,
        request: calls_pb2.StartCallerRequest,
    ) -> calls_pb2.StartCallerResponse:
        """
        Start a new caller.

        Args:
            request (calls_pb2.StartCallerRequest): The request message to start a new caller.

        Returns:
            calls_pb2.StartCallerResponse: The response message containing the caller ID and
            other details for the started caller.
        """
        return await self.stub.StartCaller(request=request, metadata=self.metadata)

    async def start_callers(
        self,
        request: calls_pb2.StartCallersRequest,
    ) -> calls_pb2.StartCallersResponse:
        """
        Start multiple callers.

        Args:
            request (calls_pb2.StartCallersRequest): The request message to start multiple callers.

        Returns:
            calls_pb2.StartCallersResponse: The response message containing the IDs and
            other details for the started callers.
        """
        return await self.stub.StartCallers(request=request, metadata=self.metadata)

    async def list_callers(
        self,
        request: calls_pb2.ListCallersRequest,
    ) -> calls_pb2.ListCallersResponse:
        """
        List all active callers.

        Args:
            request (calls_pb2.ListCallersRequest): The request message to list active callers.

        Returns:
            calls_pb2.ListCallersResponse: The response message containing a list of active callers.
        """
        return await self.stub.ListCallers(request=request, metadata=self.metadata)

    async def get_caller(
        self,
        request: calls_pb2.GetCallerRequest,
    ) -> calls_pb2.Caller:
        """
        Get details of a specific caller.

        Args:
            request (calls_pb2.GetCallerRequest): The request message to get details of a caller.

        Returns:
            calls_pb2.Caller: The response message containing the details of the specified caller.
        """
        return await self.stub.GetCaller(request=request, metadata=self.metadata)

    async def delete_caller(
        self,
        request: calls_pb2.DeleteCallersRequest,
    ) -> calls_pb2.DeleteCallersResponse:
        """
        Delete multiple callers.

        Args:
            request (calls_pb2.DeleteCallersRequest): The request message to delete multiple callers.

        Returns:
            calls_pb2.DeleteCallersResponse: The response message containing the IDs and
            other details for the deleted callers.
        """
        return await self.stub.DeleteCallers(request=request, metadata=self.metadata)

    async def delete_callers(
        self,
        request: calls_pb2.DeleteCallersRequest,
    ) -> calls_pb2.DeleteCallersResponse:
        """
        Delete multiple callers.

        Args:
            request (calls_pb2.DeleteCallersRequest): The request message to delete multiple callers.

        Returns:
            calls_pb2.DeleteCallersResponse: The response message containing the IDs and
            other details for the deleted callers.
        """
        return await self.stub.DeleteCallers(request=request, metadata=self.metadata)

    async def stop_caller(
        self,
        request: calls_pb2.StopCallersRequest,
    ) -> calls_pb2.StopCallersResponse:
        """
        Stop multiple callers.

        Args:
            request (calls_pb2.StopCallersRequest): The request message to stop multiple callers.

        Returns:
            calls_pb2.StopCallersResponse: The response message containing the IDs and
            other details for the stopd callers.
        """
        return await self.stub.StopCallers(request=request, metadata=self.metadata)

    async def stop_callers(
        self,
        request: calls_pb2.StopCallersRequest,
    ) -> calls_pb2.StopCallersResponse:
        """
        Stop multiple callers.

        Args:
            request (calls_pb2.StopCallersRequest): The request message to stop multiple callers.

        Returns:
            calls_pb2.StopCallersResponse: The response message containing the IDs and
            other details for the stopd callers.
        """
        return await self.stub.StopCallers(request=request, metadata=self.metadata)

    async def start_listener(
        self,
        request: calls_pb2.StartListenerRequest,
    ) -> calls_pb2.StartListenerResponse:
        """
        Start a new listener.

        Args:
            request (calls_pb2.StartListenerRequest): The request message to start a new listener.

        Returns:
            calls_pb2.StartListenerResponse: The response message containing the listener ID and
            other details for the started listener.
        """
        return await self.stub.StartListener(request=request, metadata=self.metadata)

    async def start_listeners(
        self,
        request: calls_pb2.StartListenersRequest,
    ) -> calls_pb2.StartListenersResponse:
        """
        Start multiple listeners.

        Args:
            request (calls_pb2.StartListenersRequest): The request message to start multiple listeners.

        Returns:
            calls_pb2.StartListenersResponse: The response message containing the IDs and
            other details for the started listeners.
        """
        return await self.stub.StartListeners(request=request, metadata=self.metadata)

    async def list_listeners(
        self,
        request: calls_pb2.ListListenersRequest,
    ) -> calls_pb2.ListListenersResponse:
        """
        List all active listeners.

        Args:
            request (calls_pb2.ListListenersRequest): The request message to list active listeners.

        Returns:
            calls_pb2.ListListenersResponse: The response message containing a list of active listeners.
        """
        return await self.stub.ListListeners(request=request, metadata=self.metadata)

    async def get_listener(
        self,
        request: calls_pb2.GetListenerRequest,
    ) -> calls_pb2.Listener:
        """
        Get details of a specific listener.

        Args:
            request (calls_pb2.GetListenerRequest): The request message to get details of a listener.

        Returns:
            calls_pb2.Listener: The response message containing the details of the specified listener.
        """
        return await self.stub.GetListener(request=request, metadata=self.metadata)

    async def delete_listener(
        self,
        request: calls_pb2.DeleteListenersRequest,
    ) -> calls_pb2.DeleteListenersResponse:
        """
        Delete multiple listeners.

        Args:
            request (calls_pb2.DeleteListenersRequest): The request message to delete multiple listeners.

        Returns:
            calls_pb2.DeleteListenersResponse: The response message containing the IDs and
            other details for the deleted listeners.
        """
        return await self.stub.DeleteListeners(request=request, metadata=self.metadata)

    async def delete_listeners(
        self,
        request: calls_pb2.DeleteListenersRequest,
    ) -> calls_pb2.DeleteListenersResponse:
        """
        Delete multiple listeners.

        Args:
            request (calls_pb2.DeleteListenersRequest): The request message to delete multiple listeners.

        Returns:
            calls_pb2.DeleteListenersResponse: The response message containing the IDs and
            other details for the deleted listeners.
        """
        return await self.stub.DeleteListeners(request=request, metadata=self.metadata)

    async def stop_listener(
        self,
        request: calls_pb2.StopListenersRequest,
    ) -> calls_pb2.StopListenersResponse:
        """
        Stop multiple listeners.

        Args:
            request (calls_pb2.StopListenersRequest): The request message to stop multiple listeners.

        Returns:
            calls_pb2.StopListenersResponse: The response message containing the IDs and
            other details for the stopd listeners.
        """
        return await self.stub.StopListeners(request=request, metadata=self.metadata)

    async def stop_listeners(
        self,
        request: calls_pb2.StopListenersRequest,
    ) -> calls_pb2.StopListenersResponse:
        """
        Stop multiple listeners.

        Args:
            request (calls_pb2.StopListenersRequest): The request message to stop multiple listeners.

        Returns:
            calls_pb2.StopListenersResponse: The response message containing the IDs and
            other details for the stopd listeners.
        """
        return await self.stub.StopListeners(request=request, metadata=self.metadata)

    async def start_scheduled_caller(
        self, request: calls_pb2.StartScheduledCallerRequest
    ) -> calls_pb2.StartScheduledCallerResponse:
        """
        Start a new scheduled caller.

        Args:
            request (calls_pb2.StartScheduledCallerRequest): The request message to start a new scheduled caller.

        Returns:
            calls_pb2.StartScheduledCallerResponse: The response message containing the scheduled caller ID and
            other details for the started scheduled caller.
        """
        return await self.stub.StartScheduledCaller(request=request, metadata=self.metadata)

    async def start_scheduled_callers(
        self,
        request: calls_pb2.StartScheduledCallersRequest,
    ) -> calls_pb2.StartScheduledCallersResponse:
        """
        Start multiple scheduled callers.

        Args:
            request (calls_pb2.StartScheduledCallersRequest): The request message to start multiple scheduled callers.

        Returns:
            calls_pb2.StartScheduledCallersResponse: The response message containing the IDs and
            other details for the started scheduled callers.
        """
        return await self.stub.StartScheduledCallers(request=request, metadata=self.metadata)

    async def stop_call(
        self,
        request: calls_pb2.StopCallRequest,
    ) -> calls_pb2.StopCallResponse:
        """
        Stop an active call.

        Args:
            request (calls_pb2.StopCallRequest): The request message to stop an active call.

        Returns:
            calls_pb2.StopCallResponse: The response message containing the details of the stopped call.
        """
        return await self.stub.StopCall(request=request, metadata=self.metadata)

    async def stop_calls(
        self,
        request: calls_pb2.StopCallsRequest,
    ) -> calls_pb2.StopCallsResponse:
        """
        Stop multiple active calls.

        Args:
            request (calls_pb2.StopCallsRequest): The request message to stop multiple active calls.

        Returns:
            calls_pb2.StopCallsResponse: The response message containing the details of the stopped calls.
        """
        return await self.stub.StopCalls(request=request, metadata=self.metadata)

    async def stop_all_calls(
        self,
        request: calls_pb2.StopAllCallsRequest,
    ) -> calls_pb2.StopCallsResponse:
        """
        Stop all active calls.

        Args:
            request (calls_pb2.StopAllCallsRequest): The request message to stop all active calls.

        Returns:
            calls_pb2.StopCallsResponse: The response message containing the details of the stopped calls.
        """
        return await self.stub.StopAllCalls(request=request, metadata=self.metadata)

    async def transfer_call(
        self,
        request: calls_pb2.TransferCallRequest,
    ) -> calls_pb2.TransferCallResponse:
        """
        Transfer an active call to a different entity.

        Args:
            request (calls_pb2.TransferCallRequest): The request message to transfer an active call.

        Returns:
            calls_pb2.TransferCallResponse: The response message containing the details of the transferred call.
        """
        return await self.stub.TransferCall(request=request, metadata=self.metadata)

    async def transfer_calls(
        self,
        request: calls_pb2.TransferCallsRequest,
    ) -> calls_pb2.TransferCallsResponse:
        """
        Transfer multiple active calls to different entities.

        Args:
            request (calls_pb2.TransferCallsRequest): The request message to transfer multiple active calls.

        Returns:
            calls_pb2.TransferCallsResponse: The response message containing the details of the transferred calls.
        """
        return await self.stub.TransferCalls(request=request, metadata=self.metadata)

    async def get_call(self, request: calls_pb2.GetCallRequest) -> calls_pb2.Call:
        """
        Get details of a specific call.

        Args:
            request (calls_pb2.GetCallRequest): The request message to get details of a call.

        Returns:
            calls_pb2.Call: The response message containing the details of the specified call.
        """
        return await self.stub.GetCall(request=request, metadata=self.metadata)

    async def list_calls(
        self,
        request: calls_pb2.ListCallsRequest,
    ) -> calls_pb2.ListCallsResponse:
        """
        List all active calls.

        Args:
            request (calls_pb2.ListCallsRequest): The request message to list active calls.

        Returns:
            calls_pb2.ListCallsResponse: The response message containing a list of active calls.
        """
        return await self.stub.ListCalls(request=request, metadata=self.metadata)

    def stream_caller_status(
        self,
        request: calls_pb2.StreamCallerStatusRequest,
    ) -> AsyncIterator[calls_pb2.StreamCallResourceStatusResponse]:
        """
        Stream the SIP status, including its description, of the callers of a project as it changes.

        This method is deliberately NOT ``async def``: a server-streaming call returns an async
        iterator, not a coroutine. Use it as ``async for response in calls.stream_caller_status(request)``,
        and call ``.cancel()`` on the returned object to release the server-side stream slot early.

        Args:
            request (calls_pb2.StreamCallerStatusRequest):
                The request specifying the project and the callers to watch.

        Returns:
            AsyncIterator[calls_pb2.StreamCallResourceStatusResponse]:
                An async iterator over the status envelopes.
        """
        response: AsyncIterator[calls_pb2.StreamCallResourceStatusResponse] = self.stub.StreamCallerStatus(
            request=request,
            metadata=self.metadata,
        )
        return response

    def stream_listener_status(
        self,
        request: calls_pb2.StreamListenerStatusRequest,
    ) -> AsyncIterator[calls_pb2.StreamCallResourceStatusResponse]:
        """
        Stream the SIP status, including its description, of the listeners of a project as it changes.

        This method is deliberately NOT ``async def``: a server-streaming call returns an async
        iterator, not a coroutine. Use it as ``async for response in calls.stream_listener_status(request)``,
        and call ``.cancel()`` on the returned object to release the server-side stream slot early.

        Args:
            request (calls_pb2.StreamListenerStatusRequest):
                The request specifying the project and the listeners to watch.

        Returns:
            AsyncIterator[calls_pb2.StreamCallResourceStatusResponse]:
                An async iterator over the status envelopes.
        """
        response: AsyncIterator[calls_pb2.StreamCallResourceStatusResponse] = self.stub.StreamListenerStatus(
            request=request,
            metadata=self.metadata,
        )
        return response

    def stream_scheduled_caller_status(
        self,
        request: calls_pb2.StreamScheduledCallerStatusRequest,
    ) -> AsyncIterator[calls_pb2.StreamCallResourceStatusResponse]:
        """
        Stream the status of the scheduled callers of a project as it changes.

        This method is deliberately NOT ``async def``: a server-streaming call returns an async
        iterator, not a coroutine. Use it as ``async for response in calls.stream_scheduled_caller_status(request)``,
        and call ``.cancel()`` on the returned object to release the server-side stream slot early.

        Args:
            request (calls_pb2.StreamScheduledCallerStatusRequest):
                The request specifying the project and the scheduled callers to watch.

        Returns:
            AsyncIterator[calls_pb2.StreamCallResourceStatusResponse]:
                An async iterator over the status envelopes.
        """
        response: AsyncIterator[calls_pb2.StreamCallResourceStatusResponse] = self.stub.StreamScheduledCallerStatus(
            request=request,
            metadata=self.metadata,
        )
        return response
