"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class PhonemizerId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___PhonemizerId = PhonemizerId

class CustomPhonemizerProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    MAPS_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    @property
    def maps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Map]: ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        maps : typing.Optional[typing.Iterable[global___Map]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","maps",b"maps"]) -> None: ...
global___CustomPhonemizerProto = CustomPhonemizerProto

class Map(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WORD_FIELD_NUMBER: builtins.int
    PHONEME_GROUPS_FIELD_NUMBER: builtins.int
    word: typing.Text = ...
    phoneme_groups: typing.Text = ...
    def __init__(self,
        *,
        word : typing.Text = ...,
        phoneme_groups : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["phoneme_groups",b"phoneme_groups","word",b"word"]) -> None: ...
global___Map = Map

class ListCustomPhonemizerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PHONEMIZERS_FIELD_NUMBER: builtins.int
    @property
    def phonemizers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CustomPhonemizerProto]: ...
    def __init__(self,
        *,
        phonemizers : typing.Optional[typing.Iterable[global___CustomPhonemizerProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["phonemizers",b"phonemizers"]) -> None: ...
global___ListCustomPhonemizerResponse = ListCustomPhonemizerResponse

class ListCustomPhonemizerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PIPELINE_IDS_FIELD_NUMBER: builtins.int
    @property
    def pipeline_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        pipeline_ids : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pipeline_ids",b"pipeline_ids"]) -> None: ...
global___ListCustomPhonemizerRequest = ListCustomPhonemizerRequest

class UpdateCustomPhonemizerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class UpdateMethod(_UpdateMethod, metaclass=_UpdateMethodEnumTypeWrapper):
        """extend hard will add new words replacing those that are already in phonemizer
        extend soft will add new words only if they are not yet in phonemizer
        replace will clean all the words in the phonemizer and then add new ones
        """
        pass
    class _UpdateMethod:
        V = typing.NewType('V', builtins.int)
    class _UpdateMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UpdateMethod.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        extend_hard = UpdateCustomPhonemizerRequest.UpdateMethod.V(0)
        extend_soft = UpdateCustomPhonemizerRequest.UpdateMethod.V(1)
        replace = UpdateCustomPhonemizerRequest.UpdateMethod.V(2)

    extend_hard = UpdateCustomPhonemizerRequest.UpdateMethod.V(0)
    extend_soft = UpdateCustomPhonemizerRequest.UpdateMethod.V(1)
    replace = UpdateCustomPhonemizerRequest.UpdateMethod.V(2)

    ID_FIELD_NUMBER: builtins.int
    UPDATE_METHOD_FIELD_NUMBER: builtins.int
    MAPS_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    update_method: global___UpdateCustomPhonemizerRequest.UpdateMethod.V = ...
    @property
    def maps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Map]: ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        update_method : global___UpdateCustomPhonemizerRequest.UpdateMethod.V = ...,
        maps : typing.Optional[typing.Iterable[global___Map]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","maps",b"maps","update_method",b"update_method"]) -> None: ...
global___UpdateCustomPhonemizerRequest = UpdateCustomPhonemizerRequest

class CreateCustomPhonemizerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PREFIX_FIELD_NUMBER: builtins.int
    MAPS_FIELD_NUMBER: builtins.int
    prefix: typing.Text = ...
    @property
    def maps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Map]: ...
    def __init__(self,
        *,
        prefix : typing.Text = ...,
        maps : typing.Optional[typing.Iterable[global___Map]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["maps",b"maps","prefix",b"prefix"]) -> None: ...
global___CreateCustomPhonemizerRequest = CreateCustomPhonemizerRequest
