# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ondewo.vtsi import call_log_pb2 as ondewo_dot_vtsi_dot_call__log__pb2


class VoipCallLogsStub(object):
    """call log endpoints to be used by ondewo-sip-sim instances to transfer their log info to the voip manager
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartVoipLog = channel.unary_unary(
                '/ondewo.nlu.VoipCallLogs/StartVoipLog',
                request_serializer=ondewo_dot_vtsi_dot_call__log__pb2.StartVoipLogRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.FromString,
                )
        self.FinishVoipLog = channel.unary_unary(
                '/ondewo.nlu.VoipCallLogs/FinishVoipLog',
                request_serializer=ondewo_dot_vtsi_dot_call__log__pb2.FinishVoipLogRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.FromString,
                )
        self.UpdateVoipLog = channel.unary_unary(
                '/ondewo.nlu.VoipCallLogs/UpdateVoipLog',
                request_serializer=ondewo_dot_vtsi_dot_call__log__pb2.UpdateVoipLogRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.FromString,
                )
        self.GetVoipLog = channel.unary_unary(
                '/ondewo.nlu.VoipCallLogs/GetVoipLog',
                request_serializer=ondewo_dot_vtsi_dot_call__log__pb2.GetVoipLogRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.GetVoipLogResponse.FromString,
                )
        self.GetManifestVoipLog = channel.unary_unary(
                '/ondewo.nlu.VoipCallLogs/GetManifestVoipLog',
                request_serializer=ondewo_dot_vtsi_dot_call__log__pb2.GetManifestVoipLogRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.ManifestVoipLog.FromString,
                )
        self.ActivateSaveCallLogs = channel.unary_unary(
                '/ondewo.nlu.VoipCallLogs/ActivateSaveCallLogs',
                request_serializer=ondewo_dot_vtsi_dot_call__log__pb2.SaveCallLogsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.SaveCallLogsResponse.FromString,
                )


class VoipCallLogsServicer(object):
    """call log endpoints to be used by ondewo-sip-sim instances to transfer their log info to the voip manager
    """

    def StartVoipLog(self, request, context):
        """// get all call IDs associated with a sip-id [PROTOTYPE IF MULTIPLE CALLS PER SIP INSTANCE ARE REALIZED, REMOVED FOR CLARITY]
        rpc GetCallIds (GetCallIdsRequest) returns (GetCallIdsResponse) {
        option (google.api.http) = {
        post: "/v2/{session=projects/*/agent/sessions/*}:GetCallIds"
        body: "*"
        };
        }

        start logging of a call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishVoipLog(self, request, context):
        """finish logging of a call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVoipLog(self, request, context):
        """update logging of a call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoipLog(self, request, context):
        """get call log for single call instance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManifestVoipLog(self, request, context):
        """get call log of manifest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateSaveCallLogs(self, request, context):
        """activate saving call logs in the voip manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoipCallLogsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartVoipLog': grpc.unary_unary_rpc_method_handler(
                    servicer.StartVoipLog,
                    request_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.StartVoipLogRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.SerializeToString,
            ),
            'FinishVoipLog': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishVoipLog,
                    request_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.FinishVoipLogRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.SerializeToString,
            ),
            'UpdateVoipLog': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVoipLog,
                    request_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.UpdateVoipLogRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.SerializeToString,
            ),
            'GetVoipLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoipLog,
                    request_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.GetVoipLogRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_call__log__pb2.GetVoipLogResponse.SerializeToString,
            ),
            'GetManifestVoipLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifestVoipLog,
                    request_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.GetManifestVoipLogRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_call__log__pb2.ManifestVoipLog.SerializeToString,
            ),
            'ActivateSaveCallLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateSaveCallLogs,
                    request_deserializer=ondewo_dot_vtsi_dot_call__log__pb2.SaveCallLogsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_call__log__pb2.SaveCallLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ondewo.nlu.VoipCallLogs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoipCallLogs(object):
    """call log endpoints to be used by ondewo-sip-sim instances to transfer their log info to the voip manager
    """

    @staticmethod
    def StartVoipLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.VoipCallLogs/StartVoipLog',
            ondewo_dot_vtsi_dot_call__log__pb2.StartVoipLogRequest.SerializeToString,
            ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinishVoipLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.VoipCallLogs/FinishVoipLog',
            ondewo_dot_vtsi_dot_call__log__pb2.FinishVoipLogRequest.SerializeToString,
            ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVoipLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.VoipCallLogs/UpdateVoipLog',
            ondewo_dot_vtsi_dot_call__log__pb2.UpdateVoipLogRequest.SerializeToString,
            ondewo_dot_vtsi_dot_call__log__pb2.VoipLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVoipLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.VoipCallLogs/GetVoipLog',
            ondewo_dot_vtsi_dot_call__log__pb2.GetVoipLogRequest.SerializeToString,
            ondewo_dot_vtsi_dot_call__log__pb2.GetVoipLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetManifestVoipLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.VoipCallLogs/GetManifestVoipLog',
            ondewo_dot_vtsi_dot_call__log__pb2.GetManifestVoipLogRequest.SerializeToString,
            ondewo_dot_vtsi_dot_call__log__pb2.ManifestVoipLog.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActivateSaveCallLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.VoipCallLogs/ActivateSaveCallLogs',
            ondewo_dot_vtsi_dot_call__log__pb2.SaveCallLogsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_call__log__pb2.SaveCallLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
