# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ondewo.vtsi import calls_pb2 as ondewo_dot_vtsi_dot_calls__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ondewo/vtsi/calls_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallsStub(object):
    """<p>ONDEWO VTSI API</p>
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/StartCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerResponse.FromString,
                _registered_method=True)
        self.StartCallers = channel.unary_unary(
                '/ondewo.vtsi.Calls/StartCallers',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersResponse.FromString,
                _registered_method=True)
        self.ListCallers = channel.unary_unary(
                '/ondewo.vtsi.Calls/ListCallers',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersResponse.FromString,
                _registered_method=True)
        self.GetCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/GetCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.Caller.FromString,
                _registered_method=True)
        self.DeleteCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/DeleteCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerResponse.FromString,
                _registered_method=True)
        self.DeleteCallers = channel.unary_unary(
                '/ondewo.vtsi.Calls/DeleteCallers',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersResponse.FromString,
                _registered_method=True)
        self.StopCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerResponse.FromString,
                _registered_method=True)
        self.StopCallers = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopCallers',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersResponse.FromString,
                _registered_method=True)
        self.StartListener = channel.unary_unary(
                '/ondewo.vtsi.Calls/StartListener',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerResponse.FromString,
                _registered_method=True)
        self.StartListeners = channel.unary_unary(
                '/ondewo.vtsi.Calls/StartListeners',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersResponse.FromString,
                _registered_method=True)
        self.StopListener = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopListener',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerResponse.FromString,
                _registered_method=True)
        self.StopListeners = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopListeners',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersResponse.FromString,
                _registered_method=True)
        self.ListListeners = channel.unary_unary(
                '/ondewo.vtsi.Calls/ListListeners',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersResponse.FromString,
                _registered_method=True)
        self.GetListener = channel.unary_unary(
                '/ondewo.vtsi.Calls/GetListener',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetListenerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.Listener.FromString,
                _registered_method=True)
        self.DeleteListener = channel.unary_unary(
                '/ondewo.vtsi.Calls/DeleteListener',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerResponse.FromString,
                _registered_method=True)
        self.DeleteListeners = channel.unary_unary(
                '/ondewo.vtsi.Calls/DeleteListeners',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersResponse.FromString,
                _registered_method=True)
        self.StartScheduledCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/StartScheduledCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerResponse.FromString,
                _registered_method=True)
        self.StartScheduledCallers = channel.unary_unary(
                '/ondewo.vtsi.Calls/StartScheduledCallers',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersResponse.FromString,
                _registered_method=True)
        self.AddCallersToCampaign = channel.unary_unary(
                '/ondewo.vtsi.Calls/AddCallersToCampaign',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.AddCallersToCampaignRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.AddCallersToCampaignResponse.FromString,
                _registered_method=True)
        self.AddScheduledCallersToCampaign = channel.unary_unary(
                '/ondewo.vtsi.Calls/AddScheduledCallersToCampaign',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.AddScheduledCallersToCampaignRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.AddScheduledCallersToCampaignResponse.FromString,
                _registered_method=True)
        self.GetScheduledCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/GetScheduledCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetScheduledCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ScheduledCaller.FromString,
                _registered_method=True)
        self.ListScheduledCallers = channel.unary_unary(
                '/ondewo.vtsi.Calls/ListScheduledCallers',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListScheduledCallersRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListScheduledCallersResponse.FromString,
                _registered_method=True)
        self.CancelScheduledCaller = channel.unary_unary(
                '/ondewo.vtsi.Calls/CancelScheduledCaller',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.CancelScheduledCallerRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.CancelScheduledCallerResponse.FromString,
                _registered_method=True)
        self.StopCall = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopCall',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallResponse.FromString,
                _registered_method=True)
        self.StopCalls = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopCalls',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
                _registered_method=True)
        self.StopAllCalls = channel.unary_unary(
                '/ondewo.vtsi.Calls/StopAllCalls',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopAllCallsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
                _registered_method=True)
        self.TransferCall = channel.unary_unary(
                '/ondewo.vtsi.Calls/TransferCall',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallResponse.FromString,
                _registered_method=True)
        self.TransferCalls = channel.unary_unary(
                '/ondewo.vtsi.Calls/TransferCalls',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsResponse.FromString,
                _registered_method=True)
        self.GetCall = channel.unary_unary(
                '/ondewo.vtsi.Calls/GetCall',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.Call.FromString,
                _registered_method=True)
        self.ListCalls = channel.unary_unary(
                '/ondewo.vtsi.Calls/ListCalls',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsResponse.FromString,
                _registered_method=True)
        self.StreamCallerStatus = channel.unary_stream(
                '/ondewo.vtsi.Calls/StreamCallerStatus',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallerStatusRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.FromString,
                _registered_method=True)
        self.StreamListenerStatus = channel.unary_stream(
                '/ondewo.vtsi.Calls/StreamListenerStatus',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamListenerStatusRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.FromString,
                _registered_method=True)
        self.StreamScheduledCallerStatus = channel.unary_stream(
                '/ondewo.vtsi.Calls/StreamScheduledCallerStatus',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamScheduledCallerStatusRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.FromString,
                _registered_method=True)
        self.InviteToCall = channel.unary_unary(
                '/ondewo.vtsi.Calls/InviteToCall',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.InviteToCallRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.InviteToCallResponse.FromString,
                _registered_method=True)
        self.RemoveCallParticipant = channel.unary_unary(
                '/ondewo.vtsi.Calls/RemoveCallParticipant',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.RemoveCallParticipantRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.RemoveCallParticipantResponse.FromString,
                _registered_method=True)
        self.SetCallMediaControl = channel.unary_unary(
                '/ondewo.vtsi.Calls/SetCallMediaControl',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.SetCallMediaControlRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.SetCallMediaControlResponse.FromString,
                _registered_method=True)
        self.StreamCallAudio = channel.stream_stream(
                '/ondewo.vtsi.Calls/StreamCallAudio',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioResponse.FromString,
                _registered_method=True)
        self.ListenCallAudio = channel.unary_stream(
                '/ondewo.vtsi.Calls/ListenCallAudio',
                request_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListenCallAudioRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioResponse.FromString,
                _registered_method=True)


class CallsServicer(object):
    """<p>ONDEWO VTSI API</p>
    """

    def StartCaller(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Caller and Listener endpoints
        ////////////////////////////////////////////////////////////////////////////

        <p>Start single caller instance for a specific nlu-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCallers(self, request, context):
        """<p>Start multiple ondewo-sip callers instances for a specific nlu-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCallers(self, request, context):
        """<p>Lists all available callers</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCaller(self, request, context):
        """<p>Gets a caller</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCaller(self, request, context):
        """<p>Deletes a caller</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCallers(self, request, context):
        """<p>Deletes multiple callers</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCaller(self, request, context):
        """<p>Stops a caller</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCallers(self, request, context):
        """<p>Stops multiple callers</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartListener(self, request, context):
        """<p>Start single listener instance for a specific nlu-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartListeners(self, request, context):
        """<p>Start multiple ondewo-sip listeners instances for a specific nlu-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopListener(self, request, context):
        """<p>Stop a ondewo-sip listeners instances for a specific nlu-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopListeners(self, request, context):
        """<p>Stop multiple ondewo-sip listeners instances for a specific nlu-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListListeners(self, request, context):
        """<p>Lists all available listeners</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListener(self, request, context):
        """<p>Gets a listener</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteListener(self, request, context):
        """<p>Deletes a listener</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteListeners(self, request, context):
        """<p>Deletes multiple listeners</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScheduledCaller(self, request, context):
        """<p>Start a single ondewo-sip caller instance at a scheduled time</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScheduledCallers(self, request, context):
        """<p>Start multiple ondewo-sip caller instances, each at its own scheduled time</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCallersToCampaign(self, request, context):
        """<p>Adds callers to a campaign instead of starting them. The campaign then starts them, at most
        <code>max_parallel_calls</code> at a time. The request is atomic: either the campaign (when new), every
        campaign call is stored, or nothing is. Errors are gRPC status codes (see <code>CampaignAssignment</code>).</p>
        <p>Rolling updates: a VTSI server that predates this RPC answers <code>UNIMPLEMENTED</code> and starts
        nothing. Do not fall back to <code>StartCallers</code> on <code>UNIMPLEMENTED</code>; retry later.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddScheduledCallersToCampaign(self, request, context):
        """<p>Adds scheduled callers to a campaign: each fires at or after its scheduled time AND when the campaign has a
        free slot, and follows the campaign&apos;s retries, stop and hard stop. Same atomicity, errors and rolling-update
        behaviour as <code>AddCallersToCampaign</code>.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduledCaller(self, request, context):
        """<p>Gets a scheduled caller</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScheduledCallers(self, request, context):
        """<p>Lists the scheduled callers of a vtsi-project</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelScheduledCaller(self, request, context):
        """<p>Cancels a scheduled caller that has not fired yet</p>
        <p>A scheduled caller of a campaign can be cancelled while its campaign call is
        <code>CAMPAIGN_CALL_STATE_NOT_STARTED</code> or <code>CAMPAIGN_CALL_STATE_RETRY_PENDING</code>;
        the campaign call then becomes <code>CAMPAIGN_CALL_STATE_CANCELLED</code>. While an attempt is
        <code>DISPATCHING</code> or <code>IN_PROGRESS</code> the request is refused:
        <code>cancelled = false</code> and the scheduled caller keeps its status.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCall(self, request, context):
        """<p>Stop/kill a ondewo-sip listener or caller instance for a specific vtsi-project.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCalls(self, request, context):
        """<p>Stop/kill a list of ondewo-sip listener or caller instances for a specific vtsi-project.</p>
        <p>Stops both Listener and Caller calls</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAllCalls(self, request, context):
        """<p>Stop/kill all ondewo-sip listener or caller instance for a specific nlu-project.</p>
        <p>Stops all Listener and Caller calls</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferCall(self, request, context):
        """<p>Transfer a call to a phone number, a softphone account, another listener or the listener queue.</p>
        <p>The target is either the typed <code>target</code> or the legacy raw <code>transfer_id</code>, never both. It is
        resolved and validated before anything is sent; an invalid target is answered with
        <code>TRANSFER_OUTCOME_TARGET_INVALID</code> and an <code>error_reason</code>, and the call is untouched.</p>
        <p><code>TRANSFER_MODE_BLIND</code> (default) sends a SIP REFER and reports its outcome: a refused REFER keeps the
        call with the bot. <code>TRANSFER_MODE_WARM</code> rings the target into the call first, and the bot leaves only
        after the target joined (Asterisk 22 only).</p>
        <p>Telephony outcomes (busy, no answer, REFER rejected) are successful RPCs carrying an <code>outcome</code>.
        Refusals before any side effect also return a gRPC status with <code>reason=&lt;token&gt;</code> in its details:
        <code>INVALID_ARGUMENT</code> (both targets set, malformed target), <code>NOT_FOUND</code> (call or target not
        found, including another project&apos;s), <code>FAILED_PRECONDITION</code> (<code>call-not-connected</code>,
        <code>amd-in-progress</code>, <code>call-not-yet-identified</code>, <code>participants-present</code>,
        <code>asterisk-version-unsupported</code>, <code>sip-image-too-old</code>), <code>ABORTED</code>
        (<code>transfer-in-progress</code>), <code>UNAVAILABLE</code> (<code>sip-unreachable</code>).</p>
        <p>Authorization: requires the role <code>PROJECT_DEVELOPER</code> or higher on the project, and the server&apos;s
        Keycloak auth mode <code>ENFORCE</code>; otherwise <code>PERMISSION_DENIED</code>, or
        <code>FAILED_PRECONDITION</code> with <code>reason=call-supervision-requires-auth</code> when auth is not enforced.
        Every action writes an audit record (who, call, when, mode, target). No announcement is played to the caller.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferCalls(self, request, context):
        """<p>Transfer several calls, each like <code>TransferCall</code>.</p>
        <p>Authorization: requires the role <code>PROJECT_DEVELOPER</code> or higher on the project, and the server&apos;s
        Keycloak auth mode <code>ENFORCE</code>; otherwise <code>PERMISSION_DENIED</code>, or
        <code>FAILED_PRECONDITION</code> with <code>reason=call-supervision-requires-auth</code> when auth is not enforced.
        Every action writes an audit record (who, call, when, mode, target). No announcement is played to the caller.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCall(self, request, context):
        """<p>Get call log for single call instance</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCalls(self, request, context):
        """<p>Get call log for all call instances</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCallerStatus(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Status stream endpoints
        ////////////////////////////////////////////////////////////////////////////

        <p>Streams the status of the callers of a project: a snapshot first
        (<code>snapshot = true</code>), then every caller whose call or SIP status changed, plus
        keep-alive messages. Ends when the client disconnects or at the server-side maximum stream
        duration.</p>
        <p>Errors: <code>NOT_FOUND</code> for an unknown project; <code>RESOURCE_EXHAUSTED</code> when
        the server has no free stream slot.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamListenerStatus(self, request, context):
        """<p>Streams the status of the listeners of a project, like <code>StreamCallerStatus</code>.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScheduledCallerStatus(self, request, context):
        """<p>Streams the status of the scheduled callers of a project, like
        <code>StreamCallerStatus</code>. The snapshot holds every PENDING and FIRING scheduled caller
        and those that finished in the last hour.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteToCall(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Call control endpoints
        ////////////////////////////////////////////////////////////////////////////

        <p>Invite a registered softphone account of the project into a connected call. Returns the participant in
        <code>PARTICIPANT_STATE_RINGING</code>; follow <code>Call.participants</code> or the events
        <code>VTSI_EVENT_CALL_PARTICIPANT_*</code> for JOINED, FAILED and LEFT.</p>
        <p><code>PARTICIPANT_MODE_CONFERENCE</code> (default) joins the softphone into the call: Asterisk mixes the caller,
        the bot and the participant, and by default the bot keeps talking and listening
        (<code>BOT_POLICY_ON_JOIN_KEEP</code>). <code>PARTICIPANT_MODE_MONITOR</code> lets the participant listen only.
        When the bot&apos;s leg ends, every participant is hung up; the caller is handed over only by a WARM
        <code>TransferCall</code>. Idempotent per <code>request_id</code>.</p>
        <p>Errors: <code>INVALID_ARGUMENT</code>, <code>NOT_FOUND</code> (call or softphone account, including another
        project&apos;s), <code>FAILED_PRECONDITION</code> (<code>call-not-connected</code>, <code>amd-in-progress</code>,
        <code>softphone-not-registered</code>, <code>softphone-disabled</code>, <code>softphone-unrouted</code>,
        <code>call-not-yet-identified</code>, <code>bot-channel-ambiguous</code>, <code>asterisk-not-local</code>,
        <code>asterisk-version-unsupported</code>), <code>ALREADY_EXISTS</code> (the softphone is already ringing or joined),
        <code>ABORTED</code> (<code>transfer-in-progress</code>), <code>RESOURCE_EXHAUSTED</code> (participant cap),
        <code>UNAVAILABLE</code> (<code>asterisk-unreachable</code>).</p>
        <p>Authorization: requires the role <code>PROJECT_DEVELOPER</code> or higher on the project, and the server&apos;s
        Keycloak auth mode <code>ENFORCE</code>; otherwise <code>PERMISSION_DENIED</code>, or
        <code>FAILED_PRECONDITION</code> with <code>reason=call-supervision-requires-auth</code> when auth is not enforced.
        Every action writes an audit record (who, call, when, mode, target). No announcement is played to the caller.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCallParticipant(self, request, context):
        """<p>Hang up a participant of a call (ringing or joined). The participant ends as
        <code>PARTICIPANT_STATE_LEFT</code> with <code>end_reason = REMOVED</code>; the call and the bot are not
        affected.</p>
        <p>Authorization: <code>PROJECT_EXECUTOR</code> or higher. Audited like <code>InviteToCall</code>.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCallMediaControl(self, request, context):
        """<p>Mute the bot of a connected call and/or stop it listening to the caller, or undo either. Every request sets a
        desired level and never toggles: a repeat answers <code>changed = false</code>. The bot stays muted while
        anything else (a TALK take-over of <code>StreamCallAudio</code>, a participant bot policy) also holds it muted.</p>
        <p>Errors as for <code>InviteToCall</code>, plus <code>FAILED_PRECONDITION</code> <code>reason=sip-image-too-old</code>,
        <code>ABORTED</code> <code>reason=call-control-busy</code> (another call-control request for the call is running)
        and <code>UNAVAILABLE</code> <code>reason=sip-unreachable</code> or <code>reason=csi-media-control-failed</code> (the
        bot did not apply the level: a requested pause is rolled back, a requested mute is kept).</p>
        <p>Authorization: requires the role <code>PROJECT_DEVELOPER</code> or higher on the project, and the server&apos;s
        Keycloak auth mode <code>ENFORCE</code>; otherwise <code>PERMISSION_DENIED</code>, or
        <code>FAILED_PRECONDITION</code> with <code>reason=call-supervision-requires-auth</code> when auth is not enforced.
        Every action writes an audit record (who, call, when, mode, target). No announcement is played to the caller.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCallAudio(self, request_iterator, context):
        """<p>Live audio of a connected call, both ways. The first request MUST be <code>config</code> (within 2 seconds).
        LISTEN receives the caller mixed with the bot. TALK sends the agent&apos;s audio to the caller and REQUIRES
        <code>take_over</code>: the bot is muted and does not listen while the stream is connected, and resumes when it
        ends; in TALK the agent hears the caller only. Audio is LINEAR16 little-endian mono in 20 ms frames.</p>
        <p>Bidirectional streaming: available to native gRPC clients (python, nodejs) only. Browser (grpc-web) clients
        use <code>ListenCallAudio</code>, plus a softphone (<code>InviteToCall</code>) to talk.</p>
        <p>Errors: <code>INVALID_ARGUMENT</code> (no or invalid <code>config</code>, TALK without
        <code>take_over</code>, wrong frame size), <code>NOT_FOUND</code>, <code>FAILED_PRECONDITION</code>
        (<code>call-not-connected</code>, <code>amd-in-progress</code>, <code>call-not-yet-identified</code>,
        <code>bot-still-speaking</code>, <code>sip-image-too-old</code>), <code>RESOURCE_EXHAUSTED</code> (stream cap, a
        second TALK). A normal end sends one <code>ended</code> message, then OK. A second <code>config</code> or audio
        sent in LISTEN mode ends the stream with <code>INVALID_ARGUMENT</code>. A client half-close ends the stream
        (<code>CALL_AUDIO_END_REASON_CLIENT_CLOSED</code>), so a listening client keeps its request stream open.</p>
        <p>Authorization: requires the role <code>PROJECT_DEVELOPER</code> or higher on the project, and the server&apos;s
        Keycloak auth mode <code>ENFORCE</code>; otherwise <code>PERMISSION_DENIED</code>, or
        <code>FAILED_PRECONDITION</code> with <code>reason=call-supervision-requires-auth</code> when auth is not enforced.
        Every action writes an audit record (who, call, when, mode, target). No announcement is played to the caller.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenCallAudio(self, request, context):
        """<p>Listen-only live audio of a connected call, like <code>StreamCallAudio</code> in LISTEN mode, as a server
        stream that grpc-web (browser) clients can consume. <code>config.mode</code> must be LISTEN or unspecified and
        <code>config.take_over</code> must be false, otherwise <code>INVALID_ARGUMENT</code> <code>reason=listen-only</code>.</p>
        <p>Authorization: requires the role <code>PROJECT_DEVELOPER</code> or higher on the project, and the server&apos;s
        Keycloak auth mode <code>ENFORCE</code>; otherwise <code>PERMISSION_DENIED</code>, or
        <code>FAILED_PRECONDITION</code> with <code>reason=call-supervision-requires-auth</code> when auth is not enforced.
        Every action writes an audit record (who, call, when, mode, target). No announcement is played to the caller.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallerResponse.SerializeToString,
            ),
            'StartCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCallers,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartCallersResponse.SerializeToString,
            ),
            'ListCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCallers,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallersResponse.SerializeToString,
            ),
            'GetCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.Caller.SerializeToString,
            ),
            'DeleteCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerResponse.SerializeToString,
            ),
            'DeleteCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCallers,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersResponse.SerializeToString,
            ),
            'StopCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallerResponse.SerializeToString,
            ),
            'StopCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCallers,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallersResponse.SerializeToString,
            ),
            'StartListener': grpc.unary_unary_rpc_method_handler(
                    servicer.StartListener,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenerResponse.SerializeToString,
            ),
            'StartListeners': grpc.unary_unary_rpc_method_handler(
                    servicer.StartListeners,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartListenersResponse.SerializeToString,
            ),
            'StopListener': grpc.unary_unary_rpc_method_handler(
                    servicer.StopListener,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenerResponse.SerializeToString,
            ),
            'StopListeners': grpc.unary_unary_rpc_method_handler(
                    servicer.StopListeners,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopListenersResponse.SerializeToString,
            ),
            'ListListeners': grpc.unary_unary_rpc_method_handler(
                    servicer.ListListeners,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListListenersResponse.SerializeToString,
            ),
            'GetListener': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListener,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetListenerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.Listener.SerializeToString,
            ),
            'DeleteListener': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteListener,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerResponse.SerializeToString,
            ),
            'DeleteListeners': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteListeners,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersResponse.SerializeToString,
            ),
            'StartScheduledCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScheduledCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerResponse.SerializeToString,
            ),
            'StartScheduledCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScheduledCallers,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersResponse.SerializeToString,
            ),
            'AddCallersToCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCallersToCampaign,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.AddCallersToCampaignRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.AddCallersToCampaignResponse.SerializeToString,
            ),
            'AddScheduledCallersToCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.AddScheduledCallersToCampaign,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.AddScheduledCallersToCampaignRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.AddScheduledCallersToCampaignResponse.SerializeToString,
            ),
            'GetScheduledCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduledCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetScheduledCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ScheduledCaller.SerializeToString,
            ),
            'ListScheduledCallers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScheduledCallers,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListScheduledCallersRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListScheduledCallersResponse.SerializeToString,
            ),
            'CancelScheduledCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelScheduledCaller,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.CancelScheduledCallerRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.CancelScheduledCallerResponse.SerializeToString,
            ),
            'StopCall': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCall,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallResponse.SerializeToString,
            ),
            'StopCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCalls,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.SerializeToString,
            ),
            'StopAllCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAllCalls,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StopAllCallsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.SerializeToString,
            ),
            'TransferCall': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferCall,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallResponse.SerializeToString,
            ),
            'TransferCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferCalls,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.TransferCallsResponse.SerializeToString,
            ),
            'GetCall': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCall,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.GetCallRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.Call.SerializeToString,
            ),
            'ListCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCalls,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.ListCallsResponse.SerializeToString,
            ),
            'StreamCallerStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCallerStatus,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallerStatusRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.SerializeToString,
            ),
            'StreamListenerStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamListenerStatus,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamListenerStatusRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.SerializeToString,
            ),
            'StreamScheduledCallerStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScheduledCallerStatus,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamScheduledCallerStatusRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.SerializeToString,
            ),
            'InviteToCall': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteToCall,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.InviteToCallRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.InviteToCallResponse.SerializeToString,
            ),
            'RemoveCallParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCallParticipant,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.RemoveCallParticipantRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.RemoveCallParticipantResponse.SerializeToString,
            ),
            'SetCallMediaControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCallMediaControl,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.SetCallMediaControlRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.SetCallMediaControlResponse.SerializeToString,
            ),
            'StreamCallAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCallAudio,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioResponse.SerializeToString,
            ),
            'ListenCallAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCallAudio,
                    request_deserializer=ondewo_dot_vtsi_dot_calls__pb2.ListenCallAudioRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ondewo.vtsi.Calls', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ondewo.vtsi.Calls', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calls(object):
    """<p>ONDEWO VTSI API</p>
    """

    @staticmethod
    def StartCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartCaller',
            ondewo_dot_vtsi_dot_calls__pb2.StartCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartCallers',
            ondewo_dot_vtsi_dot_calls__pb2.StartCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListCallers',
            ondewo_dot_vtsi_dot_calls__pb2.ListCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetCaller',
            ondewo_dot_vtsi_dot_calls__pb2.GetCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.Caller.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteCaller',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteCallers',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCaller',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCallers',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartListener',
            ondewo_dot_vtsi_dot_calls__pb2.StartListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartListeners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartListeners',
            ondewo_dot_vtsi_dot_calls__pb2.StartListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopListener',
            ondewo_dot_vtsi_dot_calls__pb2.StopListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopListeners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopListeners',
            ondewo_dot_vtsi_dot_calls__pb2.StopListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListListeners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListListeners',
            ondewo_dot_vtsi_dot_calls__pb2.ListListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetListener',
            ondewo_dot_vtsi_dot_calls__pb2.GetListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.Listener.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteListener',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteListeners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/DeleteListeners',
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.DeleteListenersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScheduledCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartScheduledCaller',
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScheduledCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StartScheduledCallers',
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StartScheduledCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCallersToCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/AddCallersToCampaign',
            ondewo_dot_vtsi_dot_calls__pb2.AddCallersToCampaignRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.AddCallersToCampaignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddScheduledCallersToCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/AddScheduledCallersToCampaign',
            ondewo_dot_vtsi_dot_calls__pb2.AddScheduledCallersToCampaignRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.AddScheduledCallersToCampaignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduledCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetScheduledCaller',
            ondewo_dot_vtsi_dot_calls__pb2.GetScheduledCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ScheduledCaller.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScheduledCallers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListScheduledCallers',
            ondewo_dot_vtsi_dot_calls__pb2.ListScheduledCallersRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListScheduledCallersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelScheduledCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/CancelScheduledCaller',
            ondewo_dot_vtsi_dot_calls__pb2.CancelScheduledCallerRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.CancelScheduledCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCall',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopCalls',
            ondewo_dot_vtsi_dot_calls__pb2.StopCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAllCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/StopAllCalls',
            ondewo_dot_vtsi_dot_calls__pb2.StopAllCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StopCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/TransferCall',
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/TransferCalls',
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.TransferCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/GetCall',
            ondewo_dot_vtsi_dot_calls__pb2.GetCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.Call.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/ListCalls',
            ondewo_dot_vtsi_dot_calls__pb2.ListCallsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.ListCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCallerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ondewo.vtsi.Calls/StreamCallerStatus',
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallerStatusRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamListenerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ondewo.vtsi.Calls/StreamListenerStatus',
            ondewo_dot_vtsi_dot_calls__pb2.StreamListenerStatusRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScheduledCallerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ondewo.vtsi.Calls/StreamScheduledCallerStatus',
            ondewo_dot_vtsi_dot_calls__pb2.StreamScheduledCallerStatusRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallResourceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InviteToCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/InviteToCall',
            ondewo_dot_vtsi_dot_calls__pb2.InviteToCallRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.InviteToCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveCallParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/RemoveCallParticipant',
            ondewo_dot_vtsi_dot_calls__pb2.RemoveCallParticipantRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.RemoveCallParticipantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCallMediaControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Calls/SetCallMediaControl',
            ondewo_dot_vtsi_dot_calls__pb2.SetCallMediaControlRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.SetCallMediaControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCallAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ondewo.vtsi.Calls/StreamCallAudio',
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenCallAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ondewo.vtsi.Calls/ListenCallAudio',
            ondewo_dot_vtsi_dot_calls__pb2.ListenCallAudioRequest.SerializeToString,
            ondewo_dot_vtsi_dot_calls__pb2.StreamCallAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
