# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ondewo.vtsi import softphones_pb2 as ondewo_dot_vtsi_dot_softphones__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ondewo/vtsi/softphones_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SoftphonesStub(object):
    """<p>ONDEWO VTSI API</p>
    <p>Manages the SOFTPHONE ACCOUNTS of a VTSI project: SIP accounts on the project&apos;s Asterisk that
    a human uses from a softphone such as Zoiper, to call into the project&apos;s listeners or to be reached
    by the project.</p>
    <p>A softphone account is NEVER one of the <code>ondewo000N</code> accounts the per-call ondewo-sip
    containers register with: it has its own SIP credentials, its own endpoint on the Asterisk and, for
    <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, its own client certificate issued by the
    project&apos;s SOFTPHONE certificate authority.</p>
    <p><b>Secrets are handed out exactly once.</b> The SIP password and the password-protected PKCS#12
    bundle carrying the client private key appear only in the responses of
    <code>CreateSoftphoneAccount</code> and <code>RotateSoftphoneCredentials</code>. VTSI keeps no copy of
    the private key or of the PKCS#12 password, and stores the SIP password only in the form the Asterisk
    needs to verify a SIP digest. No other RPC returns a secret; a lost private key or password is
    recovered by rotating it.</p>
    <p>Errors are reported as gRPC status codes, not as <code>error_message</code> fields:
    <code>INVALID_ARGUMENT</code> for a malformed name, filter, field mask or value;
    <code>NOT_FOUND</code> for an unknown project, account or certificate;
    <code>ALREADY_EXISTS</code> for a <code>sip_username</code> already taken in the project;
    <code>FAILED_PRECONDITION</code> when the project or the account is in a state that does not allow the
    operation (each RPC names its cases); <code>ABORTED</code> when a concurrent change to the same account
    won, in which case nothing was stored and the request can be retried.</p>
    <p><b>A change that reduces access is enforced before it is acknowledged.</b> When
    <code>UpdateSoftphoneAccount</code>, <code>DeleteSoftphoneAccount</code> or
    <code>RevokeSoftphoneCertificate</code> is stored but the running Asterisk of a deployed project could
    not be updated, the RPC fails with <code>FAILED_PRECONDITION</code>; the stored change is applied by
    the next successful change or deployment. <code>CreateSoftphoneAccount</code> and
    <code>RotateSoftphoneCredentials</code> return their one-time secrets even then.</p>
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSoftphoneAccount = channel.unary_unary(
                '/ondewo.vtsi.Softphones/CreateSoftphoneAccount',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.CreateSoftphoneAccountRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.CreateSoftphoneAccountResponse.FromString,
                _registered_method=True)
        self.GetSoftphoneAccount = channel.unary_unary(
                '/ondewo.vtsi.Softphones/GetSoftphoneAccount',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneAccountRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneAccount.FromString,
                _registered_method=True)
        self.UpdateSoftphoneAccount = channel.unary_unary(
                '/ondewo.vtsi.Softphones/UpdateSoftphoneAccount',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.UpdateSoftphoneAccountRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneAccount.FromString,
                _registered_method=True)
        self.DeleteSoftphoneAccount = channel.unary_unary(
                '/ondewo.vtsi.Softphones/DeleteSoftphoneAccount',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.DeleteSoftphoneAccountRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.DeleteSoftphoneAccountResponse.FromString,
                _registered_method=True)
        self.ListSoftphoneAccounts = channel.unary_unary(
                '/ondewo.vtsi.Softphones/ListSoftphoneAccounts',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneAccountsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneAccountsResponse.FromString,
                _registered_method=True)
        self.RotateSoftphoneCredentials = channel.unary_unary(
                '/ondewo.vtsi.Softphones/RotateSoftphoneCredentials',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.RotateSoftphoneCredentialsRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.RotateSoftphoneCredentialsResponse.FromString,
                _registered_method=True)
        self.ListSoftphoneCertificates = channel.unary_unary(
                '/ondewo.vtsi.Softphones/ListSoftphoneCertificates',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneCertificatesRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneCertificatesResponse.FromString,
                _registered_method=True)
        self.GetSoftphoneCertificate = channel.unary_unary(
                '/ondewo.vtsi.Softphones/GetSoftphoneCertificate',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneCertificateRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneCertificate.FromString,
                _registered_method=True)
        self.RevokeSoftphoneCertificate = channel.unary_unary(
                '/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.RevokeSoftphoneCertificateRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneCertificate.FromString,
                _registered_method=True)
        self.GetSoftphoneProvisioning = channel.unary_unary(
                '/ondewo.vtsi.Softphones/GetSoftphoneProvisioning',
                request_serializer=ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneProvisioningRequest.SerializeToString,
                response_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneProvisioning.FromString,
                _registered_method=True)


class SoftphonesServicer(object):
    """<p>ONDEWO VTSI API</p>
    <p>Manages the SOFTPHONE ACCOUNTS of a VTSI project: SIP accounts on the project&apos;s Asterisk that
    a human uses from a softphone such as Zoiper, to call into the project&apos;s listeners or to be reached
    by the project.</p>
    <p>A softphone account is NEVER one of the <code>ondewo000N</code> accounts the per-call ondewo-sip
    containers register with: it has its own SIP credentials, its own endpoint on the Asterisk and, for
    <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, its own client certificate issued by the
    project&apos;s SOFTPHONE certificate authority.</p>
    <p><b>Secrets are handed out exactly once.</b> The SIP password and the password-protected PKCS#12
    bundle carrying the client private key appear only in the responses of
    <code>CreateSoftphoneAccount</code> and <code>RotateSoftphoneCredentials</code>. VTSI keeps no copy of
    the private key or of the PKCS#12 password, and stores the SIP password only in the form the Asterisk
    needs to verify a SIP digest. No other RPC returns a secret; a lost private key or password is
    recovered by rotating it.</p>
    <p>Errors are reported as gRPC status codes, not as <code>error_message</code> fields:
    <code>INVALID_ARGUMENT</code> for a malformed name, filter, field mask or value;
    <code>NOT_FOUND</code> for an unknown project, account or certificate;
    <code>ALREADY_EXISTS</code> for a <code>sip_username</code> already taken in the project;
    <code>FAILED_PRECONDITION</code> when the project or the account is in a state that does not allow the
    operation (each RPC names its cases); <code>ABORTED</code> when a concurrent change to the same account
    won, in which case nothing was stored and the request can be retried.</p>
    <p><b>A change that reduces access is enforced before it is acknowledged.</b> When
    <code>UpdateSoftphoneAccount</code>, <code>DeleteSoftphoneAccount</code> or
    <code>RevokeSoftphoneCertificate</code> is stored but the running Asterisk of a deployed project could
    not be updated, the RPC fails with <code>FAILED_PRECONDITION</code>; the stored change is applied by
    the next successful change or deployment. <code>CreateSoftphoneAccount</code> and
    <code>RotateSoftphoneCredentials</code> return their one-time secrets even then.</p>
    """

    def CreateSoftphoneAccount(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Softphone account endpoints
        ////////////////////////////////////////////////////////////////////////////

        <p>Creates a softphone account in a VTSI project, generates its SIP password and, for
        <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, issues its first client certificate.
        The response carries the ONE-TIME secrets; they cannot be retrieved again.</p>
        <p>If the project is deployed the account is applied to the running Asterisk; otherwise it is
        applied on the next deployment.</p>
        <p>Errors: <code>NOT_FOUND</code> if the project does not exist; <code>ALREADY_EXISTS</code> if the
        <code>sip_username</code> is taken in the project; <code>INVALID_ARGUMENT</code> for an invalid or
        reserved <code>sip_username</code>, an output-only field that was set, or an out-of-range value;
        <code>FAILED_PRECONDITION</code> if the project is being deleted, or, for
        <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, if the project has no Asterisk port yet
        or its SOFTPHONE certificate authority is unusable (a redeployment mints a new one).</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoftphoneAccount(self, request, context):
        """<p>Returns a softphone account. Never returns a secret.</p>
        <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> for a
        malformed name or an unknown <code>field_mask</code> path.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSoftphoneAccount(self, request, context):
        """<p>Updates the mutable fields of a softphone account named by <code>update_mask</code>. Credentials
        are not changed here; use <code>RotateSoftphoneCredentials</code>.</p>
        <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> for an
        empty mask, an unknown, output-only or immutable path, or an out-of-range value;
        <code>FAILED_PRECONDITION</code> when switching to
        <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> while the account has no
        <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate, or if the project is being deleted.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSoftphoneAccount(self, request, context):
        """<p>Deletes a softphone account. Its endpoint is removed from the Asterisk, its registrations are
        dropped and every certificate it holds is revoked. Deletion is permanent.</p>
        <p>Errors: <code>NOT_FOUND</code> if the account does not exist.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSoftphoneAccounts(self, request, context):
        """<p>Lists the softphone accounts of a VTSI project, filtered, sorted and paged. Never returns a
        secret.</p>
        <p>Errors: <code>NOT_FOUND</code> if the project does not exist; <code>INVALID_ARGUMENT</code> for an
        invalid filter, an unknown <code>field_mask</code> path, a negative <code>page_size</code> or a
        <code>page_token</code> that was not issued for the same project, filter and sorting.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateSoftphoneCredentials(self, request, context):
        """<p>Rotates the SIP password and/or the client certificate of a softphone account and returns the new
        ONE-TIME secrets. <b>Every rotation rotates the SIP password</b>, including one that asked only for
        <code>rotate_certificate</code>: the Asterisk has no certificate revocation list, so a previous
        certificate stops being usable for this account only because the password it was issued with
        stops working. The new password takes effect immediately and drops the account&apos;s current
        registrations, so every softphone using it must be reconfigured. A rotated certificate moves the
        previous <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate to
        <code>SOFTPHONE_CERTIFICATE_STATUS_SUPERSEDED</code>. A rotation also unlocks an account that
        <code>RevokeSoftphoneCertificate</code> locked (a <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>
        account only once it again holds an ACTIVE certificate).</p>
        <p>Rotating the certificate of a <code>SOFTPHONE_TRANSPORT_SECURITY_SERVER_TLS_ONLY</code> account is
        allowed: it issues the certificate that a later switch to
        <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> requires, and rotates the password too.</p>
        <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>INVALID_ARGUMENT</code> if
        neither <code>rotate_sip_password</code> nor <code>rotate_certificate</code> is set;
        <code>FAILED_PRECONDITION</code> if the project is being deleted, or, for
        <code>rotate_certificate</code>, if the project has no Asterisk port yet or its SOFTPHONE
        certificate authority is unusable.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSoftphoneCertificates(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Softphone certificate endpoints
        ////////////////////////////////////////////////////////////////////////////

        <p>Lists softphone client certificates, either of one softphone account or of a whole VTSI project,
        filtered and paged, newest first. Only public material is returned.</p>
        <p>Errors: <code>NOT_FOUND</code> if the project or account does not exist;
        <code>INVALID_ARGUMENT</code> if no scope is set, for an invalid filter, an unknown
        <code>field_mask</code> path, a negative <code>page_size</code> or a foreign
        <code>page_token</code>.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoftphoneCertificate(self, request, context):
        """<p>Returns one softphone client certificate. Only public material is returned.</p>
        <p>Errors: <code>NOT_FOUND</code> if the certificate does not exist; <code>INVALID_ARGUMENT</code> for
        a malformed name or an unknown <code>field_mask</code> path.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeSoftphoneCertificate(self, request, context):
        """<p>Revokes a softphone client certificate. The Asterisk has no certificate revocation list, so
        revocation is enforced on the account&apos;s SIP password rather than on the certificate: a revoked
        certificate still completes the TLS handshake on the project&apos;s mutual-TLS port, but it no longer
        gets its holder an account.</p>
        <p>Revoking the ACTIVE certificate of an account LOCKS the account, whatever its transport
        security: it is removed from the Asterisk and its registrations are dropped until
        <code>RotateSoftphoneCredentials</code> issues a new password (and, for
        <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, a new certificate). Revoking a
        SUPERSEDED certificate records the revocation only; its password was already rotated away.
        Revoking an already revoked certificate is idempotent and keeps the original revocation time and
        reason.</p>
        <p>Errors: <code>NOT_FOUND</code> if the certificate does not exist; <code>INVALID_ARGUMENT</code>
        for a malformed name or an over-long reason.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoftphoneProvisioning(self, request, context):
        """////////////////////////////////////////////////////////////////////////////
        Softphone provisioning endpoints
        ////////////////////////////////////////////////////////////////////////////

        <p>Returns everything needed to configure a softphone for an account: server, port, transport,
        outbound proxy, SIP identity, SRTP mode, codecs, the certificate authority to trust, which client
        certificate to import, and step-by-step Zoiper instructions. It never contains the SIP password or
        the private key; those were returned once by <code>CreateSoftphoneAccount</code> or
        <code>RotateSoftphoneCredentials</code>.</p>
        <p>Errors: <code>NOT_FOUND</code> if the account does not exist; <code>FAILED_PRECONDITION</code> if
        the project is not <code>DEPLOYED</code> (the host and ports describe a running Asterisk), or if a
        <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code> account has no
        <code>SOFTPHONE_CERTIFICATE_STATUS_ACTIVE</code> certificate.</p>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoftphonesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSoftphoneAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSoftphoneAccount,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.CreateSoftphoneAccountRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.CreateSoftphoneAccountResponse.SerializeToString,
            ),
            'GetSoftphoneAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoftphoneAccount,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneAccountRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneAccount.SerializeToString,
            ),
            'UpdateSoftphoneAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSoftphoneAccount,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.UpdateSoftphoneAccountRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneAccount.SerializeToString,
            ),
            'DeleteSoftphoneAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSoftphoneAccount,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.DeleteSoftphoneAccountRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.DeleteSoftphoneAccountResponse.SerializeToString,
            ),
            'ListSoftphoneAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSoftphoneAccounts,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneAccountsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneAccountsResponse.SerializeToString,
            ),
            'RotateSoftphoneCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateSoftphoneCredentials,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.RotateSoftphoneCredentialsRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.RotateSoftphoneCredentialsResponse.SerializeToString,
            ),
            'ListSoftphoneCertificates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSoftphoneCertificates,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneCertificatesRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneCertificatesResponse.SerializeToString,
            ),
            'GetSoftphoneCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoftphoneCertificate,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneCertificateRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneCertificate.SerializeToString,
            ),
            'RevokeSoftphoneCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeSoftphoneCertificate,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.RevokeSoftphoneCertificateRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneCertificate.SerializeToString,
            ),
            'GetSoftphoneProvisioning': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoftphoneProvisioning,
                    request_deserializer=ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneProvisioningRequest.FromString,
                    response_serializer=ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneProvisioning.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ondewo.vtsi.Softphones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ondewo.vtsi.Softphones', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Softphones(object):
    """<p>ONDEWO VTSI API</p>
    <p>Manages the SOFTPHONE ACCOUNTS of a VTSI project: SIP accounts on the project&apos;s Asterisk that
    a human uses from a softphone such as Zoiper, to call into the project&apos;s listeners or to be reached
    by the project.</p>
    <p>A softphone account is NEVER one of the <code>ondewo000N</code> accounts the per-call ondewo-sip
    containers register with: it has its own SIP credentials, its own endpoint on the Asterisk and, for
    <code>SOFTPHONE_TRANSPORT_SECURITY_CLIENT_CERTIFICATE</code>, its own client certificate issued by the
    project&apos;s SOFTPHONE certificate authority.</p>
    <p><b>Secrets are handed out exactly once.</b> The SIP password and the password-protected PKCS#12
    bundle carrying the client private key appear only in the responses of
    <code>CreateSoftphoneAccount</code> and <code>RotateSoftphoneCredentials</code>. VTSI keeps no copy of
    the private key or of the PKCS#12 password, and stores the SIP password only in the form the Asterisk
    needs to verify a SIP digest. No other RPC returns a secret; a lost private key or password is
    recovered by rotating it.</p>
    <p>Errors are reported as gRPC status codes, not as <code>error_message</code> fields:
    <code>INVALID_ARGUMENT</code> for a malformed name, filter, field mask or value;
    <code>NOT_FOUND</code> for an unknown project, account or certificate;
    <code>ALREADY_EXISTS</code> for a <code>sip_username</code> already taken in the project;
    <code>FAILED_PRECONDITION</code> when the project or the account is in a state that does not allow the
    operation (each RPC names its cases); <code>ABORTED</code> when a concurrent change to the same account
    won, in which case nothing was stored and the request can be retried.</p>
    <p><b>A change that reduces access is enforced before it is acknowledged.</b> When
    <code>UpdateSoftphoneAccount</code>, <code>DeleteSoftphoneAccount</code> or
    <code>RevokeSoftphoneCertificate</code> is stored but the running Asterisk of a deployed project could
    not be updated, the RPC fails with <code>FAILED_PRECONDITION</code>; the stored change is applied by
    the next successful change or deployment. <code>CreateSoftphoneAccount</code> and
    <code>RotateSoftphoneCredentials</code> return their one-time secrets even then.</p>
    """

    @staticmethod
    def CreateSoftphoneAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/CreateSoftphoneAccount',
            ondewo_dot_vtsi_dot_softphones__pb2.CreateSoftphoneAccountRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.CreateSoftphoneAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoftphoneAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/GetSoftphoneAccount',
            ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneAccountRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneAccount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSoftphoneAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/UpdateSoftphoneAccount',
            ondewo_dot_vtsi_dot_softphones__pb2.UpdateSoftphoneAccountRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneAccount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSoftphoneAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/DeleteSoftphoneAccount',
            ondewo_dot_vtsi_dot_softphones__pb2.DeleteSoftphoneAccountRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.DeleteSoftphoneAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSoftphoneAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/ListSoftphoneAccounts',
            ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneAccountsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateSoftphoneCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/RotateSoftphoneCredentials',
            ondewo_dot_vtsi_dot_softphones__pb2.RotateSoftphoneCredentialsRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.RotateSoftphoneCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSoftphoneCertificates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/ListSoftphoneCertificates',
            ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneCertificatesRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.ListSoftphoneCertificatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoftphoneCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/GetSoftphoneCertificate',
            ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneCertificateRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneCertificate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeSoftphoneCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate',
            ondewo_dot_vtsi_dot_softphones__pb2.RevokeSoftphoneCertificateRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneCertificate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoftphoneProvisioning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ondewo.vtsi.Softphones/GetSoftphoneProvisioning',
            ondewo_dot_vtsi_dot_softphones__pb2.GetSoftphoneProvisioningRequest.SerializeToString,
            ondewo_dot_vtsi_dot_softphones__pb2.SoftphoneProvisioning.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
