"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2021 - 2026 ONDEWO GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SipEndCallRequest(google.protobuf.message.Message):
    """<p>Ends an ongoing call of the active SIP session of the active SIP account</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EndCallReason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EndCallReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SipEndCallRequest._EndCallReason.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        END_CALL_REASON_UNSPECIFIED: SipEndCallRequest._EndCallReason.ValueType  # 0
        """No specific reason given. The call ends as an ordinary hangup, exactly as before this field existed"""
        ANSWERING_MACHINE: SipEndCallRequest._EndCallReason.ValueType  # 1
        """Answering machine detection decided the callee is not a person to talk to (answering machine, fax,
        network announcement, ...) and the call is hung up WITHOUT leaving a voice message. The terminal status
        of the call is <code>OUTGOING_CALL_FINISHED</code> with the description
        <code>Answering machine detected with hang up</code>
        """
        ANSWERING_MACHINE_VOICE_MESSAGE_LEFT: SipEndCallRequest._EndCallReason.ValueType  # 2
        """Answering machine detection decided the callee is an answering machine, a voice message was left on it,
        and the call is hung up afterwards (or when the voice message timeout expired). The terminal status of
        the call is <code>OUTGOING_CALL_FINISHED</code> with the description
        <code>Answering machine detected with left voice message and hang up</code>
        """

    class EndCallReason(_EndCallReason, metaclass=_EndCallReasonEnumTypeWrapper):
        """<p>Why the call is being ended</p>"""

    END_CALL_REASON_UNSPECIFIED: SipEndCallRequest.EndCallReason.ValueType  # 0
    """No specific reason given. The call ends as an ordinary hangup, exactly as before this field existed"""
    ANSWERING_MACHINE: SipEndCallRequest.EndCallReason.ValueType  # 1
    """Answering machine detection decided the callee is not a person to talk to (answering machine, fax,
    network announcement, ...) and the call is hung up WITHOUT leaving a voice message. The terminal status
    of the call is <code>OUTGOING_CALL_FINISHED</code> with the description
    <code>Answering machine detected with hang up</code>
    """
    ANSWERING_MACHINE_VOICE_MESSAGE_LEFT: SipEndCallRequest.EndCallReason.ValueType  # 2
    """Answering machine detection decided the callee is an answering machine, a voice message was left on it,
    and the call is hung up afterwards (or when the voice message timeout expired). The terminal status of
    the call is <code>OUTGOING_CALL_FINISHED</code> with the description
    <code>Answering machine detected with left voice message and hang up</code>
    """

    HARD_HANGUP_FIELD_NUMBER: builtins.int
    END_REASON_FIELD_NUMBER: builtins.int
    AMD_RESULT_FIELD_NUMBER: builtins.int
    hard_hangup: builtins.bool
    """Set to <code>True</code> to forcefully hang up the call"""
    end_reason: global___SipEndCallRequest.EndCallReason.ValueType
    """Optional: reason for ending the call. Leave unset for an ordinary hangup"""
    @property
    def amd_result(self) -> global___AnsweringMachineDetectionResult:
        """Optional: result of the answering machine detection that decided to end the call. Only meaningful together with
        <code>end_reason = ANSWERING_MACHINE</code> or <code>end_reason = ANSWERING_MACHINE_VOICE_MESSAGE_LEFT</code>;
        it is carried into <code>SipStatus.amd_result</code> of the terminal status of the call
        """

    def __init__(
        self,
        *,
        hard_hangup: builtins.bool = ...,
        end_reason: global___SipEndCallRequest.EndCallReason.ValueType = ...,
        amd_result: global___AnsweringMachineDetectionResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["amd_result", b"amd_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["amd_result", b"amd_result", "end_reason", b"end_reason", "hard_hangup", b"hard_hangup"]) -> None: ...

global___SipEndCallRequest = SipEndCallRequest

@typing.final
class SipReportAnsweringMachineDetectedRequest(google.protobuf.message.Message):
    """<p>Reports the verdict of the answering machine detection of the ongoing outgoing call</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMD_RESULT_FIELD_NUMBER: builtins.int
    @property
    def amd_result(self) -> global___AnsweringMachineDetectionResult:
        """Result of the answering machine detection. Written to <code>SipStatus.amd_result</code> of the
        <code>OUTGOING_CALL_ANSWERING_MACHINE_DETECTED</code> status of the call
        """

    def __init__(
        self,
        *,
        amd_result: global___AnsweringMachineDetectionResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["amd_result", b"amd_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["amd_result", b"amd_result"]) -> None: ...

global___SipReportAnsweringMachineDetectedRequest = SipReportAnsweringMachineDetectedRequest

@typing.final
class AnsweringMachineDetectionResult(google.protobuf.message.Message):
    """<p>Result of the answering machine detection (AMD) of an outbound call</p>
    <p>Carries identifiers from closed vocabularies only: never audio, transcript text or a phone number</p>
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Verdict:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _VerdictEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AnsweringMachineDetectionResult._Verdict.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        VERDICT_UNSPECIFIED: AnsweringMachineDetectionResult._Verdict.ValueType  # 0
        """No verdict available"""
        HUMAN: AnsweringMachineDetectionResult._Verdict.ValueType  # 1
        """A person answered the call"""
        MACHINE: AnsweringMachineDetectionResult._Verdict.ValueType  # 2
        """An answering machine or voicemail answered the call"""
        IVR: AnsweringMachineDetectionResult._Verdict.ValueType  # 3
        """An interactive voice response system (IVR) answered the call"""
        FAX: AnsweringMachineDetectionResult._Verdict.ValueType  # 4
        """A fax machine answered the call"""
        NETWORK_ANNOUNCEMENT: AnsweringMachineDetectionResult._Verdict.ValueType  # 5
        """A network announcement answered the call, e.g. "the number you have dialed is not available" """
        CALL_SCREENING: AnsweringMachineDetectionResult._Verdict.ValueType  # 6
        """A call screening service answered the call, e.g. asking the caller to state their name"""
        NO_SPEECH: AnsweringMachineDetectionResult._Verdict.ValueType  # 7
        """Nothing was said within the detection window"""
        UNKNOWN: AnsweringMachineDetectionResult._Verdict.ValueType  # 8
        """The detection could not decide"""

    class Verdict(_Verdict, metaclass=_VerdictEnumTypeWrapper):
        """<p>Who or what answered the call</p>"""

    VERDICT_UNSPECIFIED: AnsweringMachineDetectionResult.Verdict.ValueType  # 0
    """No verdict available"""
    HUMAN: AnsweringMachineDetectionResult.Verdict.ValueType  # 1
    """A person answered the call"""
    MACHINE: AnsweringMachineDetectionResult.Verdict.ValueType  # 2
    """An answering machine or voicemail answered the call"""
    IVR: AnsweringMachineDetectionResult.Verdict.ValueType  # 3
    """An interactive voice response system (IVR) answered the call"""
    FAX: AnsweringMachineDetectionResult.Verdict.ValueType  # 4
    """A fax machine answered the call"""
    NETWORK_ANNOUNCEMENT: AnsweringMachineDetectionResult.Verdict.ValueType  # 5
    """A network announcement answered the call, e.g. "the number you have dialed is not available" """
    CALL_SCREENING: AnsweringMachineDetectionResult.Verdict.ValueType  # 6
    """A call screening service answered the call, e.g. asking the caller to state their name"""
    NO_SPEECH: AnsweringMachineDetectionResult.Verdict.ValueType  # 7
    """Nothing was said within the detection window"""
    UNKNOWN: AnsweringMachineDetectionResult.Verdict.ValueType  # 8
    """The detection could not decide"""

    class _Cause:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AnsweringMachineDetectionResult._Cause.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        CAUSE_UNSPECIFIED: AnsweringMachineDetectionResult._Cause.ValueType  # 0
        """No cause available"""
        CADENCE: AnsweringMachineDetectionResult._Cause.ValueType  # 1
        """The speech cadence, e.g. a long uninterrupted greeting"""
        KEYWORD: AnsweringMachineDetectionResult._Cause.ValueType  # 2
        """A keyword or phrase typical of the verdict"""
        BEEP: AnsweringMachineDetectionResult._Cause.ValueType  # 3
        """A voicemail beep"""
        TONE: AnsweringMachineDetectionResult._Cause.ValueType  # 4
        """A tone, e.g. a fax or special information tone"""
        CADENCE_AND_KEYWORD: AnsweringMachineDetectionResult._Cause.ValueType  # 5
        """Both the speech cadence and a keyword"""
        CADENCE_AND_BEEP: AnsweringMachineDetectionResult._Cause.ValueType  # 6
        """Both the speech cadence and a voicemail beep"""
        TIMEOUT: AnsweringMachineDetectionResult._Cause.ValueType  # 7
        """The detection window ended before any other evidence decided"""
        SILENCE: AnsweringMachineDetectionResult._Cause.ValueType  # 8
        """Silence throughout the detection window"""

    class Cause(_Cause, metaclass=_CauseEnumTypeWrapper):
        """<p>Evidence that led to the verdict</p>"""

    CAUSE_UNSPECIFIED: AnsweringMachineDetectionResult.Cause.ValueType  # 0
    """No cause available"""
    CADENCE: AnsweringMachineDetectionResult.Cause.ValueType  # 1
    """The speech cadence, e.g. a long uninterrupted greeting"""
    KEYWORD: AnsweringMachineDetectionResult.Cause.ValueType  # 2
    """A keyword or phrase typical of the verdict"""
    BEEP: AnsweringMachineDetectionResult.Cause.ValueType  # 3
    """A voicemail beep"""
    TONE: AnsweringMachineDetectionResult.Cause.ValueType  # 4
    """A tone, e.g. a fax or special information tone"""
    CADENCE_AND_KEYWORD: AnsweringMachineDetectionResult.Cause.ValueType  # 5
    """Both the speech cadence and a keyword"""
    CADENCE_AND_BEEP: AnsweringMachineDetectionResult.Cause.ValueType  # 6
    """Both the speech cadence and a voicemail beep"""
    TIMEOUT: AnsweringMachineDetectionResult.Cause.ValueType  # 7
    """The detection window ended before any other evidence decided"""
    SILENCE: AnsweringMachineDetectionResult.Cause.ValueType  # 8
    """Silence throughout the detection window"""

    class _ActionTaken:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActionTakenEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AnsweringMachineDetectionResult._ActionTaken.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACTION_TAKEN_UNSPECIFIED: AnsweringMachineDetectionResult._ActionTaken.ValueType  # 0
        """No action recorded"""
        HUNG_UP: AnsweringMachineDetectionResult._ActionTaken.ValueType  # 1
        """The call was hung up"""
        CONTINUED: AnsweringMachineDetectionResult._ActionTaken.ValueType  # 2
        """The call continued as normal"""
        DETECT_ONLY: AnsweringMachineDetectionResult._ActionTaken.ValueType  # 3
        """Detection only: the verdict was recorded, but the call was not influenced by it"""
        LEFT_VOICE_MESSAGE: AnsweringMachineDetectionResult._ActionTaken.ValueType  # 4
        """A voice message was left on the answering machine, and the call was hung up afterwards"""

    class ActionTaken(_ActionTaken, metaclass=_ActionTakenEnumTypeWrapper):
        """<p>What was done because of the verdict</p>"""

    ACTION_TAKEN_UNSPECIFIED: AnsweringMachineDetectionResult.ActionTaken.ValueType  # 0
    """No action recorded"""
    HUNG_UP: AnsweringMachineDetectionResult.ActionTaken.ValueType  # 1
    """The call was hung up"""
    CONTINUED: AnsweringMachineDetectionResult.ActionTaken.ValueType  # 2
    """The call continued as normal"""
    DETECT_ONLY: AnsweringMachineDetectionResult.ActionTaken.ValueType  # 3
    """Detection only: the verdict was recorded, but the call was not influenced by it"""
    LEFT_VOICE_MESSAGE: AnsweringMachineDetectionResult.ActionTaken.ValueType  # 4
    """A voice message was left on the answering machine, and the call was hung up afterwards"""

    VERDICT_FIELD_NUMBER: builtins.int
    CAUSE_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    DECISION_MS_FIELD_NUMBER: builtins.int
    RULE_ID_FIELD_NUMBER: builtins.int
    MATCHED_CUE_IDS_FIELD_NUMBER: builtins.int
    ACTION_TAKEN_FIELD_NUMBER: builtins.int
    CALL_ID_FIELD_NUMBER: builtins.int
    verdict: global___AnsweringMachineDetectionResult.Verdict.ValueType
    """Who or what answered the call"""
    cause: global___AnsweringMachineDetectionResult.Cause.ValueType
    """Evidence that led to the verdict"""
    confidence: builtins.float
    """Confidence of the verdict, between <code>0.0</code> and <code>1.0</code>"""
    decision_ms: builtins.int
    """Time in milliseconds from the call being connected until the verdict was reached"""
    rule_id: builtins.str
    """Identifier of the detection rule that produced the verdict"""
    action_taken: global___AnsweringMachineDetectionResult.ActionTaken.ValueType
    """What was done because of the verdict"""
    call_id: builtins.str
    """Identifier of the call the result belongs to, i.e. the value of the <code>X-ondewo-vtsi-caller-call-id</code>
    header of the call. Used to match a result to its call by identity rather than by recency
    """
    @property
    def matched_cue_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Identifiers of the cues that matched, e.g. keyword or tone identifiers. Identifiers only, never transcript text"""

    def __init__(
        self,
        *,
        verdict: global___AnsweringMachineDetectionResult.Verdict.ValueType = ...,
        cause: global___AnsweringMachineDetectionResult.Cause.ValueType = ...,
        confidence: builtins.float = ...,
        decision_ms: builtins.int = ...,
        rule_id: builtins.str = ...,
        matched_cue_ids: collections.abc.Iterable[builtins.str] | None = ...,
        action_taken: global___AnsweringMachineDetectionResult.ActionTaken.ValueType = ...,
        call_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_taken", b"action_taken", "call_id", b"call_id", "cause", b"cause", "confidence", b"confidence", "decision_ms", b"decision_ms", "matched_cue_ids", b"matched_cue_ids", "rule_id", b"rule_id", "verdict", b"verdict"]) -> None: ...

global___AnsweringMachineDetectionResult = AnsweringMachineDetectionResult

@typing.final
class SipStartCallRequest(google.protobuf.message.Message):
    """<p>Request to start the call with the active SIP session of the active SIP account</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CALLEE_ID_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    callee_id: builtins.str
    """SIP account name"""
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Headers to include when starting the call"""

    def __init__(
        self,
        *,
        callee_id: builtins.str = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["callee_id", b"callee_id", "headers", b"headers"]) -> None: ...

global___SipStartCallRequest = SipStartCallRequest

@typing.final
class SipRegisterAccountRequest(google.protobuf.message.Message):
    """<p>Request for registering a SIP account at a SIP server</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    AUTH_USERNAME_FIELD_NUMBER: builtins.int
    OUTBOUND_PROXY_FIELD_NUMBER: builtins.int
    account_name: builtins.str
    """Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    """
    password: builtins.str
    """Password of the account"""
    auth_username: builtins.str
    """Optional: authentication user name"""
    outbound_proxy: builtins.str
    """Optional: outbound proxy address, e.g. <code>my.outbound.proxy.com</code>"""
    def __init__(
        self,
        *,
        account_name: builtins.str = ...,
        password: builtins.str = ...,
        auth_username: builtins.str = ...,
        outbound_proxy: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_name", b"account_name", "auth_username", b"auth_username", "outbound_proxy", b"outbound_proxy", "password", b"password"]) -> None: ...

global___SipRegisterAccountRequest = SipRegisterAccountRequest

@typing.final
class SipStartSessionRequest(google.protobuf.message.Message):
    """<p>Request for starting a new SIP session for a specified account</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    AUTO_ANSWER_INTERVAL_FIELD_NUMBER: builtins.int
    account_name: builtins.str
    """Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    """
    auto_answer_interval: builtins.int
    """Auto-answer interval in seconds. The call will be automatically answered after this interval"""
    def __init__(
        self,
        *,
        account_name: builtins.str = ...,
        auto_answer_interval: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_name", b"account_name", "auto_answer_interval", b"auto_answer_interval"]) -> None: ...

global___SipStartSessionRequest = SipStartSessionRequest

@typing.final
class SipTransferCallRequest(google.protobuf.message.Message):
    """<p>Request for transferring a call with or without headers</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TRANSFER_ID_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    transfer_id: builtins.str
    """The account name or phone number to transfer the call to"""
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """The headers to include when transferring the call"""

    def __init__(
        self,
        *,
        transfer_id: builtins.str = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["headers", b"headers", "transfer_id", b"transfer_id"]) -> None: ...

global___SipTransferCallRequest = SipTransferCallRequest

@typing.final
class SipStatus(google.protobuf.message.Message):
    """<p>Status information for a SIP account, session, or call</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StatusType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SipStatus._StatusType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NO_SESSION: SipStatus._StatusType.ValueType  # 0
        """No session is currently active"""
        REGISTERED: SipStatus._StatusType.ValueType  # 1
        """SIP account is registered at a SIP server"""
        READY: SipStatus._StatusType.ValueType  # 2
        """SIP account is ready to call"""
        INCOMING_CALL_INITIATED: SipStatus._StatusType.ValueType  # 3
        """SIP account is being called, i.e. inbound/incoming call"""
        OUTGOING_CALL_INITIATED: SipStatus._StatusType.ValueType  # 4
        """SIP account starts calling, i.e. outbound/outgoing call"""
        OUTGOING_CALL_CONNECTED: SipStatus._StatusType.ValueType  # 5
        """SIP account outbound call is connected"""
        INCOMING_CALL_CONNECTED: SipStatus._StatusType.ValueType  # 6
        """SIP account incoming call is connected"""
        TRANSFER_CALL_INITIATED: SipStatus._StatusType.ValueType  # 7
        """SIP account starts transferring the call"""
        SOFT_HANGUP_INITIATED: SipStatus._StatusType.ValueType  # 8
        """SIP account hangs up the ongoing call"""
        HARD_HANGUP_INITIATED: SipStatus._StatusType.ValueType  # 9
        """SIP account forcefully hangs up by terminating the SIP program"""
        INCOMING_CALL_FAILED: SipStatus._StatusType.ValueType  # 10
        """SIP account cannot accept the incoming call"""
        OUTGOING_CALL_FAILED: SipStatus._StatusType.ValueType  # 11
        """SIP account cannot do an outbound call"""
        INCOMING_CALL_FINISHED: SipStatus._StatusType.ValueType  # 12
        """SIP account finished the ongoing incoming call"""
        OUTGOING_CALL_FINISHED: SipStatus._StatusType.ValueType  # 13
        """SIP account finished the ongoing outgoing call"""
        SESSION_REGISTRATION_FAILED: SipStatus._StatusType.ValueType  # 14
        """Registration of SIP account to SIP server failed"""
        SESSION_STARTED: SipStatus._StatusType.ValueType  # 15
        """SIP account started a new SIP session via a SIP server"""
        SESSION_ENDED: SipStatus._StatusType.ValueType  # 16
        """SIP account ended active sip session with SIP server"""
        TRANSFER_CALL_FAILED: SipStatus._StatusType.ValueType  # 17
        """SIP account cannot transfer the call"""
        MICROPHONE_MUTED: SipStatus._StatusType.ValueType  # 18
        """Microphone is muted"""
        MICROPHONE_UNMUTED: SipStatus._StatusType.ValueType  # 19
        """Microphone is unmuted"""
        MICROPHONE_WAV_FILES_PLAYED: SipStatus._StatusType.ValueType  # 20
        """Microphone has played wav files"""
        NO_ONGOING_CALL: SipStatus._StatusType.ValueType  # 21
        """No ongoing call"""
        OUTGOING_CALL_ANSWERING_MACHINE_DETECTED: SipStatus._StatusType.ValueType  # 22
        """Answering machine detection decided the callee of the ongoing outgoing call is not a person to talk to.
        NOT terminal: the call is still up when this status is set. <code>amd_result.verdict</code> tells an
        answering machine, a fax, a network announcement, ... apart. The call then ends as
        <code>OUTGOING_CALL_FINISHED</code> carrying <code>amd_result</code> and exactly one of the descriptions
        <code>Answering machine detected with hang up</code>,
        <code>Answering machine detected with left voice message and hang up</code>,
        <code>Answering machine detected, call ended by the answering machine</code> or
        <code>Answering machine detected, call ended by the answering machine after leaving a voice message</code>
        """

    class StatusType(_StatusType, metaclass=_StatusTypeEnumTypeWrapper):
        """Types of status"""

    NO_SESSION: SipStatus.StatusType.ValueType  # 0
    """No session is currently active"""
    REGISTERED: SipStatus.StatusType.ValueType  # 1
    """SIP account is registered at a SIP server"""
    READY: SipStatus.StatusType.ValueType  # 2
    """SIP account is ready to call"""
    INCOMING_CALL_INITIATED: SipStatus.StatusType.ValueType  # 3
    """SIP account is being called, i.e. inbound/incoming call"""
    OUTGOING_CALL_INITIATED: SipStatus.StatusType.ValueType  # 4
    """SIP account starts calling, i.e. outbound/outgoing call"""
    OUTGOING_CALL_CONNECTED: SipStatus.StatusType.ValueType  # 5
    """SIP account outbound call is connected"""
    INCOMING_CALL_CONNECTED: SipStatus.StatusType.ValueType  # 6
    """SIP account incoming call is connected"""
    TRANSFER_CALL_INITIATED: SipStatus.StatusType.ValueType  # 7
    """SIP account starts transferring the call"""
    SOFT_HANGUP_INITIATED: SipStatus.StatusType.ValueType  # 8
    """SIP account hangs up the ongoing call"""
    HARD_HANGUP_INITIATED: SipStatus.StatusType.ValueType  # 9
    """SIP account forcefully hangs up by terminating the SIP program"""
    INCOMING_CALL_FAILED: SipStatus.StatusType.ValueType  # 10
    """SIP account cannot accept the incoming call"""
    OUTGOING_CALL_FAILED: SipStatus.StatusType.ValueType  # 11
    """SIP account cannot do an outbound call"""
    INCOMING_CALL_FINISHED: SipStatus.StatusType.ValueType  # 12
    """SIP account finished the ongoing incoming call"""
    OUTGOING_CALL_FINISHED: SipStatus.StatusType.ValueType  # 13
    """SIP account finished the ongoing outgoing call"""
    SESSION_REGISTRATION_FAILED: SipStatus.StatusType.ValueType  # 14
    """Registration of SIP account to SIP server failed"""
    SESSION_STARTED: SipStatus.StatusType.ValueType  # 15
    """SIP account started a new SIP session via a SIP server"""
    SESSION_ENDED: SipStatus.StatusType.ValueType  # 16
    """SIP account ended active sip session with SIP server"""
    TRANSFER_CALL_FAILED: SipStatus.StatusType.ValueType  # 17
    """SIP account cannot transfer the call"""
    MICROPHONE_MUTED: SipStatus.StatusType.ValueType  # 18
    """Microphone is muted"""
    MICROPHONE_UNMUTED: SipStatus.StatusType.ValueType  # 19
    """Microphone is unmuted"""
    MICROPHONE_WAV_FILES_PLAYED: SipStatus.StatusType.ValueType  # 20
    """Microphone has played wav files"""
    NO_ONGOING_CALL: SipStatus.StatusType.ValueType  # 21
    """No ongoing call"""
    OUTGOING_CALL_ANSWERING_MACHINE_DETECTED: SipStatus.StatusType.ValueType  # 22
    """Answering machine detection decided the callee of the ongoing outgoing call is not a person to talk to.
    NOT terminal: the call is still up when this status is set. <code>amd_result.verdict</code> tells an
    answering machine, a fax, a network announcement, ... apart. The call then ends as
    <code>OUTGOING_CALL_FINISHED</code> carrying <code>amd_result</code> and exactly one of the descriptions
    <code>Answering machine detected with hang up</code>,
    <code>Answering machine detected with left voice message and hang up</code>,
    <code>Answering machine detected, call ended by the answering machine</code> or
    <code>Answering machine detected, call ended by the answering machine after leaving a voice message</code>
    """

    @typing.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    STATUS_TYPE_FIELD_NUMBER: builtins.int
    CALLEE_ID_FIELD_NUMBER: builtins.int
    TRANSFER_CALL_ID_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    EXCEPTION_NAME_FIELD_NUMBER: builtins.int
    EXCEPTION_TRACEBACK_FIELD_NUMBER: builtins.int
    NLU_SESSION_NAME_FIELD_NUMBER: builtins.int
    AMD_RESULT_FIELD_NUMBER: builtins.int
    account_name: builtins.str
    """Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    """
    status_type: global___SipStatus.StatusType.ValueType
    """Status type"""
    callee_id: builtins.str
    """SIP account name"""
    transfer_call_id: builtins.str
    """SIP account of the transfer"""
    description: builtins.str
    """More detailed description of the status"""
    exception_name: builtins.str
    """Name of the exception"""
    exception_traceback: builtins.str
    """Traceback of the exception"""
    nlu_session_name: builtins.str
    """session name of the NLU session"""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of the status"""

    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Headers to include when calling outbound or transfer"""

    @property
    def amd_result(self) -> global___AnsweringMachineDetectionResult:
        """Result of the answering machine detection of the call. Set on
        <code>OUTGOING_CALL_ANSWERING_MACHINE_DETECTED</code> and on the terminal status of every call on which answering machine detection ran, including a
        <code>HUMAN</code> verdict; unset otherwise
        """

    def __init__(
        self,
        *,
        account_name: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        status_type: global___SipStatus.StatusType.ValueType = ...,
        callee_id: builtins.str = ...,
        transfer_call_id: builtins.str = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        description: builtins.str = ...,
        exception_name: builtins.str = ...,
        exception_traceback: builtins.str = ...,
        nlu_session_name: builtins.str = ...,
        amd_result: global___AnsweringMachineDetectionResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["amd_result", b"amd_result", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_name", b"account_name", "amd_result", b"amd_result", "callee_id", b"callee_id", "description", b"description", "exception_name", b"exception_name", "exception_traceback", b"exception_traceback", "headers", b"headers", "nlu_session_name", b"nlu_session_name", "status_type", b"status_type", "timestamp", b"timestamp", "transfer_call_id", b"transfer_call_id"]) -> None: ...

global___SipStatus = SipStatus

@typing.final
class SipStatusHistoryResponse(google.protobuf.message.Message):
    """<p>History of SIP status</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_HISTORY_FIELD_NUMBER: builtins.int
    @property
    def status_history(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SipStatus]:
        """History of SIP status"""

    def __init__(
        self,
        *,
        status_history: collections.abc.Iterable[global___SipStatus] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status_history", b"status_history"]) -> None: ...

global___SipStatusHistoryResponse = SipStatusHistoryResponse

@typing.final
class SipPlayWavFilesRequest(google.protobuf.message.Message):
    """<p>Plays a list of wav files</p>"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAV_FILES_FIELD_NUMBER: builtins.int
    @property
    def wav_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """Wav files as bytes in a list that will be played"""

    def __init__(
        self,
        *,
        wav_files: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["wav_files", b"wav_files"]) -> None: ...

global___SipPlayWavFilesRequest = SipPlayWavFilesRequest
